project_id = "ppmiandwpebzsfqqhhws"

[api]
enabled = true
port = 54321
schemas = ["public", "graphql_public"]
extra_search_path = ["public", "extensions"]
max_rows = 1000

[db]
port = 54322
shadow_port = 54320
major_version = 15

[studio]
enabled = true
port = 54323

[auth]
enabled = true
site_url = "http://localhost:3000"
additional_redirect_urls = ["https://localhost:3000"]
jwt_expiry = 3600
enable_refresh_token_rotation = true
refresh_token_reuse_interval = 10

[auth.email]
enable_signup = true
double_confirm_changes = true
enable_confirmations = true

[functions.confirm-barber-email]
verify_jwt = true

[functions.create-barber-user]
verify_jwt = true

[functions.rate-limiter]
verify_jwt = false

[functions.claude-proxy]
verify_jwt = false

[functions.send-whatsapp]
verify_jwt = false

[functions.enviar-lembretes]
verify_jwt = false

[functions.get-subscription-status]
verify_jwt = false

[functions.create-checkout-session]
verify_jwt = false

[functions.create-customer-portal]
verify_jwt = false

[functions.load-test]
verify_jwt = false

