
INSERT INTO disposable_email_domains (domain, reason, created_by) VALUES
('guerrillamail.com', 'Top serviço de email temporário', NULL),
('sharklasers.com', 'Guerrilla Mail alternativo', NULL),
('grr.la', 'Guerrilla Mail alternativo', NULL),
('guerrillamailblock.com', 'Guerrilla Mail alternativo', NULL),
('pokemail.net', 'Guerrilla Mail alternativo', NULL),
('spam4.me', 'Guerrilla Mail alternativo', NULL),
('10minutemail.com', 'Email temporário 10 minutos', NULL),
('10minutemail.net', 'Email temporário 10 minutos', NULL),
('20minutemail.com', 'Email temporário 20 minutos', NULL),
('mailinator.com', 'Serviço muito popular', NULL),
('mailinator.net', 'Mailinator alternativo', NULL),
('mailinator2.com', 'Mailinator alternativo', NULL),
('tempmail.com', 'Temp Mail popular', NULL),
('temp-mail.org', 'Temp Mail popular', NULL),
('temp-mail.io', 'Temp Mail alternativo', NULL),
('tmpmail.org', 'Temp Mail alternativo', NULL),
('tmpmail.net', 'Temp Mail alternativo', NULL),
('throwaway.email', 'Throwaway email', NULL),
('throam.com', 'Throwaway alternativo', NULL),
('yopmail.com', 'YOPmail francês popular', NULL),
('yopmail.fr', 'YOPmail francês', NULL),
('yopmail.net', 'YOPmail alternativo', NULL),
('cool.fr.nf', 'YOPmail alternativo', NULL),
('jetable.fr.nf', 'YOPmail alternativo', NULL),
('nospam.ze.tc', 'YOPmail alternativo', NULL),
('nomail.xl.cx', 'YOPmail alternativo', NULL),
('mega.zik.dj', 'YOPmail alternativo', NULL),
('speed.1s.fr', 'YOPmail alternativo', NULL),
('maildrop.cc', 'MailDrop popular', NULL),
('maildrop.cf', 'MailDrop alternativo', NULL),
('maildrop.ga', 'MailDrop alternativo', NULL),
('maildrop.gq', 'MailDrop alternativo', NULL),
('maildrop.ml', 'MailDrop alternativo', NULL),
('getnada.com', 'GetNada popular', NULL),
('getnada.cc', 'GetNada alternativo', NULL),
('mohmal.com', 'Mohmal árabe', NULL),
('mohmal.im', 'Mohmal alternativo', NULL),
('mohmal.in', 'Mohmal alternativo', NULL),
('fentaoba.com', 'Email temporário', NULL),
('emailondeck.com', 'Email On Deck', NULL),
('mintemail.com', 'Mint Email', NULL),
('trashmail.com', 'Trash Mail', NULL),
('trashmail.de', 'Trash Mail alemão', NULL),
('trashmail.net', 'Trash Mail alternativo', NULL),
('wegwerfmail.de', 'Descartável alemão', NULL),
('wegwerfmail.net', 'Descartável alemão', NULL),
('wegwerfmail.org', 'Descartável alemão', NULL),
('tempail.com', 'Temp Mail', NULL),
('tempemail.com', 'Temp Email', NULL),
('tempemail.net', 'Temp Email alternativo', NULL),
('tempr.email', 'Tempr Email', NULL),
('tempinbox.com', 'Temp Inbox', NULL),
('fakeinbox.com', 'Fake Inbox', NULL),
('fakeinbox.net', 'Fake Inbox alternativo', NULL),
('fakemail.fr', 'Fake Mail francês', NULL),
('throwawaymail.com', 'Throwaway Mail', NULL),
('thrma.com', 'Throwaway abreviado', NULL),
('inboxbear.com', 'Inbox Bear', NULL),
('anonymousemail.me', 'Anonymous Email', NULL),
('anonymbox.com', 'Anonym Box', NULL),
('burnermail.io', 'Burner Mail', NULL),
('getairmail.com', 'AirMail', NULL),
('harakirimail.com', 'Harakiri Mail', NULL),
('armyspy.com', 'Army Spy', NULL),
('cuvox.de', 'Cuvox alemão', NULL),
('dayrep.com', 'Day Rep', NULL),
('einrot.com', 'Ein Rot alemão', NULL),
('fleckens.hu', 'Fleckens húngaro', NULL),
('gustr.com', 'Gustr', NULL),
('jourrapide.com', 'Jour Rapide francês', NULL),
('rhyta.com', 'Rhyta', NULL),
('superrito.com', 'Super Rito', NULL),
('teleworm.us', 'Teleworm', NULL),
('dispostable.com', 'Dispostable', NULL),
('disposeamail.com', 'Dispose a Mail', NULL),
('disposableaddress.com', 'Disposable Address', NULL),
('disposableinbox.com', 'Disposable Inbox', NULL),
('disposableemailaddresses.com', 'Disposable Email', NULL),
('spambox.us', 'Spam Box', NULL),
('spamgourmet.com', 'Spam Gourmet', NULL),
('spamgourmet.net', 'Spam Gourmet alternativo', NULL),
('spamgourmet.org', 'Spam Gourmet alternativo', NULL),
('incognitomail.org', 'Incognito Mail', NULL),
('incognitomail.com', 'Incognito Mail alternativo', NULL),
('thraml.com', 'Thraml', NULL),
('jetable.org', 'Jetable francês', NULL),
('jetable.com', 'Jetable alternativo', NULL),
('mailnesia.com', 'Mailnesia indonésio', NULL),
('mailcatch.com', 'Mail Catch', NULL),
('mail-temporaire.fr', 'Mail Temporaire francês', NULL),
('mail-temporaire.com', 'Mail Temporaire alternativo', NULL),
('momentics.ru', 'Momentics russo', NULL),
('receiveee.com', 'Receiveee', NULL),
('mytemp.email', 'My Temp Email', NULL),
('mytempmail.com', 'My Temp Mail', NULL),
('crazymailing.com', 'Crazy Mailing', NULL),
('dropmail.me', 'Drop Mail', NULL),
('emailtemporanea.com', 'Email temporário espanhol', NULL),
('emailtemporanea.net', 'Email temporário alternativo', NULL),
('fakeemailgenerator.com', 'Fake Email Generator', NULL),
('fakemail.net', 'Fake Mail', NULL),
('filzmail.com', 'Filz Mail', NULL),
('gishpuppy.com', 'Gish Puppy', NULL),
('great-host.in', 'Great Host', NULL),
('hidemail.de', 'Hide Mail alemão', NULL),
('imails.info', 'iMails', NULL),
('instant-mail.de', 'Instant Mail alemão', NULL),
('klzlk.com', 'KLZLK', NULL),
('kurzepost.de', 'Kurze Post alemão', NULL),
('mailbidon.com', 'Mail Bidon francês', NULL),
('maildu.de', 'Mail Du alemão', NULL),
('mailin8r.com', 'Mailin8r', NULL),
('mailmoat.com', 'Mail Moat', NULL),
('mailnull.com', 'Mail Null', NULL),
('mailsac.com', 'Mail Sac', NULL),
('mailseal.de', 'Mail Seal alemão', NULL),
('mailslite.com', 'Mails Lite', NULL),
('meltmail.com', 'Melt Mail', NULL),
('mytrashmail.com', 'My Trash Mail', NULL),
('netmails.com', 'Net Mails', NULL),
('netmails.net', 'Net Mails alternativo', NULL),
('noclickemail.com', 'No Click Email', NULL),
('nowmymail.com', 'Now My Mail', NULL),
('objectmail.com', 'Object Mail', NULL),
('oneoffemail.com', 'One Off Email', NULL),
('owlpic.com', 'Owl Pic', NULL),
('privatdemail.net', 'Privat Email alemão', NULL),
('proxymail.eu', 'Proxy Mail', NULL),
('rcpt.at', 'RCPT.at', NULL),
('safe-mail.net', 'Safe Mail', NULL),
('saynotospams.com', 'Say No To Spams', NULL),
('shieldemail.com', 'Shield Email', NULL),
('shortmail.net', 'Short Mail', NULL),
('sneakemail.com', 'Sneak Email', NULL),
('sofort-mail.de', 'Sofort Mail alemão', NULL),
('spam.la', 'Spam LA', NULL),
('spamavert.com', 'Spam Avert', NULL),
('spambob.com', 'Spam Bob', NULL),
('spambob.net', 'Spam Bob alternativo', NULL),
('spambog.com', 'Spam Bog', NULL),
('spambox.info', 'Spam Box Info', NULL),
('spamcannon.com', 'Spam Cannon', NULL),
('spamcannon.net', 'Spam Cannon alternativo', NULL),
('spamcon.org', 'Spam Con', NULL),
('spamcorptastic.com', 'Spam Corp', NULL),
('spamday.com', 'Spam Day', NULL),
('spamex.com', 'Spam Ex', NULL),
('spamfree24.com', 'Spam Free 24', NULL),
('spamfree24.de', 'Spam Free alemão', NULL),
('spamfree24.eu', 'Spam Free europeu', NULL),
('spamfree24.info', 'Spam Free Info', NULL),
('spamfree24.net', 'Spam Free Net', NULL),
('spamfree24.org', 'Spam Free Org', NULL),
('spamgrube.net', 'Spam Grube alemão', NULL),
('spamherelots.com', 'Spam Here Lots', NULL),
('spamhereplease.com', 'Spam Here Please', NULL),
('spamhole.com', 'Spam Hole', NULL),
('spamify.com', 'Spamify', NULL),
('spaminator.de', 'Spaminator alemão', NULL),
('spamkill.info', 'Spam Kill', NULL),
('spaml.com', 'Spam L', NULL),
('spaml.de', 'Spam L alemão', NULL),
('spammotel.com', 'Spam Motel', NULL),
('spamobox.com', 'Spam Obox', NULL),
('spamoff.de', 'Spam Off alemão', NULL),
('spamslicer.com', 'Spam Slicer', NULL),
('spamstack.net', 'Spam Stack', NULL),
('spamthis.co.uk', 'Spam This UK', NULL),
('spamthisplease.com', 'Spam This Please', NULL),
('spamtrail.com', 'Spam Trail', NULL),
('supergreatmail.com', 'Super Great Mail', NULL),
('supermailer.jp', 'Super Mailer japonês', NULL),
('suremail.info', 'Sure Mail', NULL),
('techemail.com', 'Tech Email', NULL),
('temp15qm.com', 'Temp 15QM', NULL),
('tempalias.com', 'Temp Alias', NULL),
('tempe-mail.com', 'Tempe Mail', NULL),
('tempemail.co.za', 'Temp Email África do Sul', NULL),
('tempemailaddress.com', 'Temp Email Address', NULL),
('tempinbox.co.uk', 'Temp Inbox UK', NULL),
('tempmaildemo.com', 'Temp Mail Demo', NULL),
('tempmailer.com', 'Temp Mailer', NULL),
('tempmailer.de', 'Temp Mailer alemão', NULL),
('tempomail.fr', 'Tempo Mail francês', NULL),
('temporarily.de', 'Temporarily alemão', NULL),
('temporarioemail.com.br', 'Temporário Email Brasil', NULL),
('temporaryemail.net', 'Temporary Email', NULL),
('temporaryemail.us', 'Temporary Email US', NULL),
('temporaryforwarding.com', 'Temporary Forwarding', NULL),
('temporaryinbox.com', 'Temporary Inbox', NULL),
('temporarymailaddress.com', 'Temporary Mail Address', NULL),
('tempthe.net', 'Temp The Net', NULL),
('thanksnospam.info', 'Thanks No Spam', NULL),
('thisisnotmyrealemail.com', 'This Is Not My Real Email', NULL),
('throwawayemailaddress.com', 'Throwaway Email Address', NULL),
('tilien.com', 'Tilien', NULL),
('tittbit.in', 'Titt Bit', NULL),
('tmailinator.com', 'TMailinator', NULL),
('trbvm.com', 'TRBVM', NULL),
('tryalert.com', 'Try Alert', NULL),
('turual.com', 'Turual', NULL),
('twinmail.de', 'Twin Mail alemão', NULL),
('tyldd.com', 'TYLDD', NULL),
('uggsrock.com', 'Uggs Rock', NULL),
('upliftnow.com', 'Uplift Now', NULL),
('uplipht.com', 'Uplipht', NULL),
('venompen.com', 'Venom Pen', NULL),
('veryrealemail.com', 'Very Real Email', NULL),
('viditag.com', 'Viditag', NULL),
('vomoto.com', 'Vomoto', NULL),
('vpn.st', 'VPN ST', NULL),
('vsimcard.com', 'VSim Card', NULL),
('vubby.com', 'Vubby', NULL),
('webemail.me', 'Web Email', NULL),
('weg-werf-email.de', 'Weg Werf alemão', NULL),
('wegwerfemail.de', 'Wegwerf Email alemão', NULL),
('wegwerfemailadresse.com', 'Wegwerf alemão', NULL),
('whyspam.me', 'Why Spam Me', NULL),
('willselfdestruct.com', 'Will Self Destruct', NULL),
('wronghead.com', 'Wrong Head', NULL),
('wuzup.net', 'Wuz Up', NULL),
('wuzupmail.net', 'Wuzup Mail', NULL),
('xagloo.com', 'Xagloo', NULL),
('xemaps.com', 'Xemaps', NULL),
('xents.com', 'Xents', NULL),
('xmaily.com', 'Xmaily', NULL),
('xoxy.net', 'Xoxy', NULL),
('yapped.net', 'Yapped', NULL),
('yopmail.gq', 'YOPmail GQ', NULL),
('yuurok.com', 'Yuurok', NULL),
('zehnminuten.de', 'Zehn Minuten alemão', NULL),
('zehnminutenmail.de', 'Zehn Minuten Mail alemão', NULL),
('zippymail.info', 'Zippy Mail', NULL),
('zoemail.com', 'Zoe Mail', NULL),
('zoemail.net', 'Zoe Mail Net', NULL),
('zomg.info', 'ZOMG', NULL),
('0-mail.com', 'Zero Mail', NULL),
('0815.ru', '0815 russo', NULL),
('0clickemail.com', 'Zero Click Email', NULL),
('0wnd.net', 'Zero WND', NULL),
('0wnd.org', 'Zero WND Org', NULL),
('10mail.org', '10 Mail', NULL),
('123-m.com', '123 M', NULL),
('1ce.us', '1CE US', NULL),
('1chuan.com', '1 Chuan chinês', NULL),
('1mail.ml', '1 Mail ML', NULL),
('1pad.de', '1 Pad alemão', NULL),
('20mail.eu', '20 Mail EU', NULL),
('20mail.in', '20 Mail India', NULL),
('20mail.it', '20 Mail Itália', NULL),
('24hourmail.com', '24 Hour Mail', NULL),
('2prong.com', '2 Prong', NULL),
('30minutemail.com', '30 Minute Mail', NULL),
('33mail.com', '33 Mail', NULL),
('3d-painting.com', '3D Painting', NULL),
('3mail.ga', '3 Mail GA', NULL),
('4warding.com', '4warding', NULL),
('4warding.net', '4warding Net', NULL),
('4warding.org', '4warding Org', NULL),
('5mail.cf', '5 Mail CF', NULL),
('5mail.ga', '5 Mail GA', NULL),
('60minutemail.com', '60 Minute Mail', NULL),
('672643.net', '672643 Net', NULL),
('675hosting.com', '675 Hosting', NULL),
('675hosting.net', '675 Hosting Net', NULL),
('675hosting.org', '675 Hosting Org', NULL),
('6ip.us', '6 IP US', NULL),
('6paq.com', '6 PAQ', NULL),
('6url.com', '6 URL', NULL),
('75hosting.com', '75 Hosting', NULL),
('75hosting.net', '75 Hosting Net', NULL),
('75hosting.org', '75 Hosting Org', NULL),
('7tags.com', '7 Tags', NULL),
('8127ep.com', '8127 EP', NULL),
('99experts.com', '99 Experts', NULL),
('9mail.cf', '9 Mail CF', NULL),
('a-bc.net', 'ABC Net', NULL),
('abusemail.de', 'Abuse Mail alemão', NULL),
('abyssmail.com', 'Abyss Mail', NULL),
('acentri.com', 'Acentri', NULL),
('advantimo.com', 'Advantimo', NULL),
('afrobacon.com', 'Afro Bacon', NULL),
('agedmail.com', 'Aged Mail', NULL),
('akapost.com', 'Aka Post', NULL),
('akerd.com', 'Akerd', NULL),
('aligamel.com', 'Ali Gamel', NULL),
('amail.com', 'A Mail', NULL),
('amail4.me', 'A Mail 4 Me', NULL),
('anappthat.com', 'An App That', NULL),
('ano-mail.net', 'Ano Mail', NULL),
('anon-mail.de', 'Anon Mail alemão', NULL),
('anonbox.net', 'Anon Box', NULL),
('anonymail.dk', 'Anonymail dinamarquês', NULL),
('anonymize.com', 'Anonymize', NULL),
('antichef.com', 'Anti Chef', NULL),
('antichef.net', 'Anti Chef Net', NULL),
('antireg.com', 'Anti Reg', NULL),
('antireg.ru', 'Anti Reg russo', NULL),
('antispam.de', 'Anti Spam alemão', NULL),
('antispammail.de', 'Anti Spam Mail alemão', NULL),
('beddly.com', 'Beddly', NULL),
('beefmilk.com', 'Beef Milk', NULL),
('bigstring.com', 'Big String', NULL),
('binkmail.com', 'Bink Mail', NULL),
('bio-muesli.net', 'Bio Muesli alemão', NULL),
('bladesmail.net', 'Blades Mail', NULL),
('bloatbox.com', 'Bloat Box', NULL),
('bobmail.info', 'Bob Mail', NULL),
('bofthew.com', 'Bofthew', NULL),
('bootybay.de', 'Booty Bay alemão', NULL),
('boun.cr', 'Boun CR', NULL),
('bouncr.com', 'Bouncr', NULL),
('brefmail.com', 'Bref Mail', NULL),
('brennendesreich.de', 'Brennendes Reich alemão', NULL),
('bsnow.net', 'B Snow', NULL),
('bspamfree.org', 'B Spam Free', NULL),
('bugmenot.com', 'Bug Me Not', NULL),
('bund.us', 'Bund US', NULL),
('burstmail.info', 'Burst Mail', NULL),
('buymoreplays.com', 'Buy More Plays', NULL),
('byom.de', 'BYOM alemão', NULL),
('c2.hu', 'C2 húngaro', NULL),
('cachedot.net', 'Cache Dot', NULL),
('casualdx.com', 'Casual DX', NULL),
('cek.pm', 'CEK PM', NULL),
('centermail.com', 'Center Mail', NULL),
('centermail.net', 'Center Mail Net', NULL),
('chacuo.net', 'Chacuo chinês', NULL),
('chammy.info', 'Chammy', NULL),
('chogmail.com', 'Chog Mail', NULL),
('choicemail1.com', 'Choice Mail 1', NULL),
('clixser.com', 'Clixser', NULL),
('cmail.net', 'C Mail', NULL),
('cmail.org', 'C Mail Org', NULL),
('coldemail.info', 'Cold Email', NULL),
('consumerriot.com', 'Consumer Riot', NULL),
('cosmorph.com', 'Cosmorph', NULL),
('courrieltemporaire.com', 'Courriel Temporaire francês', NULL),
('crapmail.org', 'Crap Mail', NULL),
('crazespaces.pw', 'Craze Spaces', NULL),
('d3p.dk', 'D3P dinamarquês', NULL),
('dacoolest.com', 'Da Coolest', NULL),
('dandikmail.com', 'Dandik Mail', NULL),
('dcemail.com', 'DC Email', NULL),
('deadaddress.com', 'Dead Address', NULL),
('deadfake.cf', 'Dead Fake CF', NULL),
('deadfake.ga', 'Dead Fake GA', NULL),
('deadfake.ml', 'Dead Fake ML', NULL),
('deadfake.tk', 'Dead Fake TK', NULL),
('deadspam.com', 'Dead Spam', NULL),
('deagot.com', 'Deagot', NULL),
('dealja.com', 'Dealja', NULL),
('despam.it', 'Despam Itália', NULL),
('despammed.com', 'Despammed', NULL),
('devnullmail.com', 'Dev Null Mail', NULL),
('dfgh.net', 'DFGH', NULL),
('digitalsanctuary.com', 'Digital Sanctuary', NULL),
('discardmail.com', 'Discard Mail', NULL),
('discardmail.de', 'Discard Mail alemão', NULL),
('disposable-email.ml', 'Disposable Email ML', NULL),
('dodgeit.com', 'Dodge It', NULL),
('dodgit.com', 'Dodgit', NULL),
('dodgit.org', 'Dodgit Org', NULL),
('donemail.ru', 'Done Mail russo', NULL),
('dontreg.com', 'Dont Reg', NULL),
('dontsendmespam.de', 'Dont Send Me Spam alemão', NULL),
('drdrb.com', 'Dr DRB', NULL),
('drdrb.net', 'Dr DRB Net', NULL),
('dump-email.info', 'Dump Email', NULL),
('dumpandjunk.com', 'Dump And Junk', NULL),
('dumpmail.de', 'Dump Mail alemão', NULL),
('dumpyemail.com', 'Dumpy Email', NULL),
('e4ward.com', 'E4ward', NULL),
('easytrashmail.com', 'Easy Trash Mail', NULL),
('einmalmail.de', 'Einmal Mail alemão', NULL),
('einrot.de', 'Einrot alemão DE', NULL),
('eintagsmail.de', 'Eintags Mail alemão', NULL),
('email-fake.cf', 'Email Fake CF', NULL),
('email-fake.com', 'Email Fake', NULL),
('email-fake.ga', 'Email Fake GA', NULL),
('email-fake.gq', 'Email Fake GQ', NULL),
('email-fake.ml', 'Email Fake ML', NULL),
('email-fake.tk', 'Email Fake TK', NULL),
('email60.com', 'Email 60', NULL),
('emaildienst.de', 'Email Dienst alemão', NULL),
('emailgo.de', 'Email Go alemão', NULL),
('emailias.com', 'Emailias', NULL),
('emailinfive.com', 'Email In Five', NULL),
('emaillime.com', 'Email Lime', NULL),
('emailmiser.com', 'Email Miser', NULL),
('emailproxsy.com', 'Email Proxsy', NULL),
('emails.ga', 'Emails GA', NULL),
('emailsensei.com', 'Email Sensei', NULL),
('emailsingularity.net', 'Email Singularity', NULL),
('emailspam.cf', 'Email Spam CF', NULL),
('emailspam.ga', 'Email Spam GA', NULL),
('emailspam.gq', 'Email Spam GQ', NULL),
('emailspam.ml', 'Email Spam ML', NULL),
('emailspam.tk', 'Email Spam TK', NULL),
('emailtemporar.ro', 'Email Temporar romeno', NULL),
('emailtemporario.com.br', 'Email Temporário Brasil', NULL),
('emailthe.net', 'Email The Net', NULL),
('emailtmp.com', 'Email Tmp', NULL),
('emailwarden.com', 'Email Warden', NULL),
('emailxfer.com', 'Email Xfer', NULL),
('emeil.in', 'Emeil India', NULL),
('emeil.ir', 'Emeil iraniano', NULL),
('ephemail.net', 'Ephemail', NULL),
('evopo.com', 'Evopo', NULL),
('explodemail.com', 'Explode Mail', NULL),
('eyepaste.com', 'Eye Paste', NULL),
('facebook-email.cf', 'Facebook Email CF', NULL),
('facebook-email.ga', 'Facebook Email GA', NULL),
('facebook-email.ml', 'Facebook Email ML', NULL),
('facebookmail.gq', 'Facebook Mail GQ', NULL),
('facebookmail.ml', 'Facebook Mail ML', NULL),
('fadingemail.com', 'Fading Email', NULL),
('fakebox.org', 'Fake Box', NULL),
('fakedemail.com', 'Faked Email', NULL),
('fakeemail.com', 'Fake Email', NULL),
('fammix.com', 'Fammix', NULL),
('fansworldwide.de', 'Fans Worldwide alemão', NULL),
('fantasymail.de', 'Fantasy Mail alemão', NULL),
('fastacura.com', 'Fast Acura', NULL),
('fastchevy.com', 'Fast Chevy', NULL),
('fastchrysler.com', 'Fast Chrysler', NULL),
('fastkawasaki.com', 'Fast Kawasaki', NULL),
('fastmazda.com', 'Fast Mazda', NULL),
('fastmitsubishi.com', 'Fast Mitsubishi', NULL),
('fastnissan.com', 'Fast Nissan', NULL),
('fastsubaru.com', 'Fast Subaru', NULL),
('fastsuzuki.com', 'Fast Suzuki', NULL),
('fasttoyota.com', 'Fast Toyota', NULL),
('fastyamaha.com', 'Fast Yamaha', NULL),
('fightallspam.com', 'Fight All Spam', NULL),
('fixmail.tk', 'Fix Mail TK', NULL),
('fizmail.com', 'Fiz Mail', NULL),
('freeletter.me', 'Free Letter', NULL),
('freemails.cf', 'Free Mails CF', NULL),
('freemails.ga', 'Free Mails GA', NULL),
('freemails.ml', 'Free Mails ML', NULL),
('garliclife.com', 'Garlic Life', NULL),
('get1mail.com', 'Get 1 Mail', NULL),
('get2mail.fr', 'Get 2 Mail francês', NULL),
('getonemail.com', 'Get One Email', NULL),
('getonemail.net', 'Get One Email Net', NULL),
('ghosttexter.de', 'Ghost Texter alemão', NULL),
('giantmail.de', 'Giant Mail alemão', NULL),
('greensloth.com', 'Green Sloth', NULL),
('guerillamail.biz', 'Guerilla Mail Biz', NULL),
('guerillamail.de', 'Guerilla Mail alemão', NULL),
('guerillamail.net', 'Guerilla Mail Net', NULL),
('guerillamail.org', 'Guerilla Mail Org', NULL),
('guerrillamail.info', 'Guerrilla Mail Info', NULL),
('hacccc.com', 'Hacccc', NULL),
('haltospam.com', 'Halt O Spam', NULL),
('hartbot.de', 'Hart Bot alemão', NULL),
('hatespam.org', 'Hate Spam', NULL),
('hidzz.com', 'Hidzz', NULL),
('hmamail.com', 'HMA Mail', NULL),
('hopemail.biz', 'Hope Mail Biz', NULL),
('hotpop.com', 'Hot Pop', NULL),
('hulapla.de', 'Hula Pla alemão', NULL),
('ieh-mail.de', 'IEH Mail alemão', NULL),
('ihateyoualot.info', 'I Hate You A Lot', NULL),
('iheartspam.org', 'I Heart Spam', NULL),
('imgof.com', 'Img Of', NULL),
('imgv.de', 'IMGV alemão', NULL),
('imstations.com', 'IM Stations', NULL),
('inbax.tk', 'Inbax TK', NULL),
('inboxalias.com', 'Inbox Alias', NULL),
('inboxclean.com', 'Inbox Clean', NULL),
('inboxclean.org', 'Inbox Clean Org', NULL),
('inboxed.im', 'Inboxed IM', NULL),
('inboxed.pw', 'Inboxed PW', NULL),
('inboxstore.me', 'Inbox Store', NULL),
('incognitomail.net', 'Incognito Mail Net', NULL),
('infectmail.com', 'Infect Mail', NULL),
('iroid.com', 'Iroid', NULL),
('jnxjn.com', 'JNXJN', NULL),
('junk1e.com', 'Junk 1E', NULL),
('junkmail.ga', 'Junk Mail GA', NULL),
('junkmail.gq', 'Junk Mail GQ', NULL),
('kasmail.com', 'Kas Mail', NULL),
('kaspop.com', 'Kas Pop', NULL),
('keepmymail.com', 'Keep My Mail', NULL),
('killmail.com', 'Kill Mail', NULL),
('killmail.net', 'Kill Mail Net', NULL),
('klassmaster.com', 'Klass Master', NULL),
('klassmaster.net', 'Klass Master Net', NULL),
('koszmail.pl', 'Kosz Mail polonês', NULL),
('kulturbetrieb.info', 'Kultur Betrieb alemão', NULL),
('l33r.eu', 'L33R EU', NULL),
('lackmail.net', 'Lack Mail', NULL),
('lackmail.ru', 'Lack Mail russo', NULL),
('lags.us', 'Lags US', NULL),
('landmail.co', 'Land Mail', NULL),
('lastmail.co', 'Last Mail', NULL),
('lastmail.com', 'Last Mail Com', NULL),
('lazyinbox.com', 'Lazy Inbox', NULL),
('letthemeatspam.com', 'Let Them Eat Spam', NULL),
('lhsdv.com', 'LHSDV', NULL),
('lifebyfood.com', 'Life By Food', NULL),
('link2mail.net', 'Link 2 Mail', NULL),
('litedrop.com', 'Lite Drop', NULL),
('login-email.cf', 'Login Email CF', NULL),
('login-email.ga', 'Login Email GA', NULL),
('login-email.ml', 'Login Email ML', NULL),
('login-email.tk', 'Login Email TK', NULL),
('lolfreak.net', 'LOL Freak', NULL),
('lookugly.com', 'Look Ugly', NULL),
('lortemail.dk', 'Lort Email dinamarquês', NULL),
('lovemeleaveme.com', 'Love Me Leave Me', NULL),
('lr78.com', 'LR78', NULL),
('lroid.com', 'Lroid', NULL),
('m21.cc', 'M21 CC', NULL),
('m4ilweb.info', 'M4il Web', NULL),
('maboard.com', 'Maboard', NULL),
('mail-easy.fr', 'Mail Easy francês', NULL),
('mail-filter.com', 'Mail Filter', NULL),
('mail1a.de', 'Mail 1A alemão', NULL),
('mail21.cc', 'Mail 21 CC', NULL),
('mail2rss.org', 'Mail 2 RSS', NULL),
('mail333.com', 'Mail 333', NULL),
('mail4trash.com', 'Mail 4 Trash', NULL),
('mailblocks.com', 'Mail Blocks', NULL),
('mailbucket.org', 'Mail Bucket', NULL),
('mailcat.biz', 'Mail Cat Biz', NULL),
('mailde.de', 'Mail DE alemão', NULL),
('mailde.info', 'Mail DE Info', NULL),
('maildx.com', 'Mail DX', NULL),
('maileater.com', 'Mail Eater', NULL),
('mailed.ro', 'Mailed romeno', NULL),
('maileimer.de', 'Mail Eimer alemão', NULL),
('mailexpire.com', 'Mail Expire', NULL),
('mailforspam.com', 'Mail For Spam', NULL),
('mailfreeonline.com', 'Mail Free Online', NULL),
('mailguard.me', 'Mail Guard', NULL),
('mailhazard.com', 'Mail Hazard', NULL),
('mailhazard.us', 'Mail Hazard US', NULL),
('mailhz.me', 'Mail HZ', NULL),
('mailimate.com', 'Mailimate', NULL),
('mailinater.com', 'Mailinater', NULL),
('mailincubator.com', 'Mail Incubator', NULL),
('mailismagic.com', 'Mail Is Magic', NULL),
('mailjunk.cf', 'Mail Junk CF', NULL),
('mailjunk.ga', 'Mail Junk GA', NULL),
('mailjunk.gq', 'Mail Junk GQ', NULL),
('mailjunk.ml', 'Mail Junk ML', NULL),
('mailjunk.tk', 'Mail Junk TK', NULL),
('mailmate.com', 'Mail Mate', NULL),
('mailme.gq', 'Mail Me GQ', NULL),
('mailme.ir', 'Mail Me iraniano', NULL),
('mailme.lv', 'Mail Me LV', NULL),
('mailme24.com', 'Mail Me 24', NULL),
('mailmetrash.com', 'Mail Me Trash', NULL),
('mailms.com', 'Mail MS', NULL),
('mailnator.com', 'Mailnator', NULL),
('mailorg.org', 'Mail Org', NULL),
('mailpick.biz', 'Mail Pick Biz', NULL),
('mailproxsy.com', 'Mail Proxsy', NULL),
('mailquack.com', 'Mail Quack', NULL),
('mailrock.biz', 'Mail Rock Biz', NULL),
('mailscrap.com', 'Mail Scrap', NULL),
('mailshell.com', 'Mail Shell', NULL),
('mailsiphon.com', 'Mail Siphon', NULL),
('mailslapping.com', 'Mail Slapping', NULL),
('mailtemp.info', 'Mail Temp Info', NULL),
('mailtome.de', 'Mail To Me alemão', NULL),
('mailtothis.com', 'Mail To This', NULL),
('mailtrash.net', 'Mail Trash', NULL),
('mailtv.net', 'Mail TV', NULL),
('mailtv.tv', 'Mail TV TV', NULL),
('mailzi.ru', 'Mailzi russo', NULL),
('mailzilla.com', 'Mailzilla', NULL),
('mailzilla.org', 'Mailzilla Org', NULL),
('makemetheking.com', 'Make Me The King', NULL),
('manybrain.com', 'Many Brain', NULL),
('mbx.cc', 'MBX CC', NULL),
('meinspamschutz.de', 'Mein Spam Schutz alemão', NULL),
('messagebeamer.de', 'Message Beamer alemão', NULL),
('ministry-of-silly-walks.de', 'Ministry Of Silly Walks alemão', NULL),
('misterpinball.de', 'Mister Pinball alemão', NULL),
('moncourrier.fr.nf', 'Mon Courrier francês', NULL),
('monemail.fr.nf', 'Mon Email francês', NULL),
('monmail.fr.nf', 'Mon Mail francês', NULL),
('monumentmail.com', 'Monument Mail', NULL),
('myalias.pw', 'My Alias PW', NULL),
('mycleaninbox.net', 'My Clean Inbox', NULL),
('myemailboxy.com', 'My Email Boxy', NULL),
('mymail-in.net', 'My Mail In', NULL),
('mymailoasis.com', 'My Mail Oasis', NULL),
('mynetstore.de', 'My Net Store alemão', NULL),
('mypacks.net', 'My Packs', NULL),
('mypartyclip.de', 'My Party Clip alemão', NULL),
('myphantomemail.com', 'My Phantom Email', NULL),
('mysamp.de', 'My Samp alemão', NULL),
('myspamless.com', 'My Spamless', NULL),
('mywarnernet.net', 'My Warner Net', NULL),
('nabuma.com', 'Nabuma', NULL),
('neomailbox.com', 'Neo Mailbox', NULL),
('nepwk.com', 'NEPWK', NULL),
('nervmich.net', 'Nerv Mich alemão', NULL),
('nervtmich.net', 'Nervt Mich alemão', NULL),
('netzidiot.de', 'Netz Idiot alemão', NULL),
('neverbox.com', 'Never Box', NULL),
('nevermail.de', 'Never Mail alemão', NULL),
('nice-4u.com', 'Nice 4 U', NULL),
('nmail.cf', 'N Mail CF', NULL),
('no-spam.ws', 'No Spam WS', NULL),
('nobulk.com', 'No Bulk', NULL),
('nogmailspam.info', 'No Gmail Spam', NULL),
('nomail.pw', 'No Mail PW', NULL),
('nomail2me.com', 'No Mail 2 Me', NULL),
('nomorespamemails.com', 'No More Spam Emails', NULL),
('nonspam.eu', 'Non Spam EU', NULL),
('nonspammer.de', 'Non Spammer alemão', NULL),
('nospam4.us', 'No Spam 4 US', NULL),
('nospamfor.us', 'No Spam For US', NULL),
('nospammail.net', 'No Spam Mail', NULL),
('nospamthanks.info', 'No Spam Thanks', NULL),
('notmailinator.com', 'Not Mailinator', NULL),
('notsharingmy.info', 'Not Sharing My Info', NULL),
('nowhere.org', 'Nowhere', NULL),
('nurfuerspam.de', 'Nur Fuer Spam alemão', NULL),
('nwldx.com', 'NWLDX', NULL),
('obobbo.com', 'Obobbo', NULL),
('odnorazovoe.ru', 'Odnorazovoe russo', NULL),
('onebiginbox.com', 'One Big Inbox', NULL),
('onewaymail.com', 'One Way Mail', NULL),
('opayq.com', 'Opayq', NULL),
('otherinbox.com', 'Other Inbox', NULL),
('outlawspam.com', 'Outlaw Spam', NULL),
('pancakemail.com', 'Pancake Mail', NULL),
('pjjkp.com', 'PJJKP', NULL),
('plexolan.de', 'Plexolan alemão', NULL),
('politikerclub.de', 'Politiker Club alemão', NULL),
('pookmail.com', 'Pook Mail', NULL),
('privacy.net', 'Privacy Net', NULL),
('privy-mail.com', 'Privy Mail', NULL),
('privymail.de', 'Privy Mail alemão', NULL),
('prtnx.com', 'PRTNX', NULL),
('prtz.eu', 'PRTZ EU', NULL),
('punkass.com', 'Punk Ass', NULL),
('putthisinyourspamdatabase.com', 'Put This In Your Spam Database', NULL),
('pwrby.com', 'PWRBY', NULL)
ON CONFLICT (domain) DO NOTHING;
